name: Test and Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  FLUTTER_VERSION: "3.x"

jobs:
  test:
    name: Analyze and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
      - run: flutter --version
      - run: flutter clean
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_android:
    name: Build Flutter (Android)
    needs: [test]
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11"
      JAVA_DISTRIBUTION: "zulu"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build appbundle

  build_ios:
    name: Build Flutter (iOS)
    needs: [test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          architecture: x64
          cache: true
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
